name: ecommerce_test
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  
  cached_network_image: ^3.2.3
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  currency_text_input_formatter: ^2.2.3
  dio: ^5.4.1
  flutter_rating_stars: ^1.0.3+4
  flutter_riverpod: ^2.4.10
  flutter_screenutil: ^5.9.0
  flutter_staggered_animations: ^1.1.1
  flutter_styled_toast: ^2.2.1
  flutter_svg_provider: ^1.0.7
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  get_it: ^7.1.3
  google_fonts: ^6.2.1
  intl: ^0.19.0
  top_snackbar_flutter: ^3.0.0+1
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svgs/
    - assets/icons/

  
